create table person_role
(
    id   int primary key generated by default as identity,
    name varchar(50) not null
);

create table person
(
    id          int primary key generated by default as identity,
    login       varchar(100) not null unique,
    password    varchar(255) not null,
    first_name  varchar(50)  not null,
    last_name   varchar(50)  not null,
    role_id     int          references person_role (id) on delete set null,
    external_id varchar(30)  not null unique
);

create table store
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null unique check (length(name) >= 2),
    external_id varchar(30)  not null unique
);

create table product_category
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null unique,
    external_id varchar(30)  not null unique
);

create table product
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null unique,
    category_id int          references product_category (id) on delete set null,
    unit        float8       not null,
    external_id varchar(30)  not null unique
);

create table purchase
(
    id           int primary key generated by default as identity,
    price        money       not null,
    purchased_at date        not null,
    product_id   int         references product (id) on delete set null,
    store_id     int         references store (id) on delete set null,
    memo         varchar(200),
    external_id  varchar(30) not null unique
);