----- DDL
drop table if exists person_role cascade;
create table person_role
(
    id   int primary key generated by default as identity,
    name varchar(50) not null
);

drop table if exists person cascade;
create table person
(
    id          int primary key generated by default as identity,
    login       varchar(100) not null unique,
    password    varchar(255) not null,
    first_name  varchar(50)  not null,
    last_name   varchar(50)  not null,
    role_id     int          references person_role (id) on delete set null,
    external_id varchar(30)  not null unique
);

drop table if exists store cascade;
create table store
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null unique check (length(name) >= 2),
    external_id varchar(30)  not null unique
);


drop table if exists product_category cascade;
create table product_category
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null unique,
    external_id varchar(30)  not null unique
);

drop table if exists product cascade;
create table product
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null,
    category_id int          references product_category (id) on delete set null,
    unit        float8       not null check ( unit > 0),
    external_id varchar(30)  not null unique,
    unique (name, category_id)
);

drop table if exists purchase cascade;
create table purchase
(
    id           int primary key generated by default as identity,
    price        decimal     not null check (price > 0),
    unit         float8      not null check ( unit > 0),
    purchased_at timestamp   not null,
    product_id   int         references product (id) on delete set null,
    store_id     int         references store (id) on delete set null,
    memo         varchar(200),
    person_id    int         references person (id) on delete set null,
    external_id  varchar(30) not null unique,
    unique (purchased_at, product_id, store_id, person_id)
);
----- DML
insert into person_role(name)
values ('ROLE_USER');
insert into person_role(name)
values ('ROLE_ADMIN');

insert into person (login, password, first_name, last_name, role_id, external_id)
values ('user', 'pwd', 'FirstUser', 'LastUser', 1, 'person1');
insert into person (login, password, first_name, last_name, role_id, external_id)
values ('admin', 'pwd', 'FirstAdmin', 'LastAdmin', 2, 'person2');


insert into store(name, external_id)
values ('Пятёрочка', 's1');
insert into store(name, external_id)
values ('Окей', 's2');
insert into store(name, external_id)
values ('Лента', 's3');

insert into product_category(name, external_id)
values ('Продукты', 'pc1');
insert into product_category(name, external_id)
values ('Хозтовары', 'pc2');
insert into product_category(name, external_id)
values ('Коммунальные услуги', 'pc3');

insert into product(name, category_id, unit, external_id)
values ('Хлеб ржаной', 1, 1, 'p1');
insert into product(name, category_id, unit, external_id)
values ('Хлеб белый', 1, 1, 'p2');
insert into product(name, category_id, unit, external_id)
values ('Кефир', 1, 1, 'p3');
insert into product(name, category_id, unit, external_id)
values ('Молоко', 1, 1, 'p4');
insert into product(name, category_id, unit, external_id)
values ('Колбаса Докторская', 1, 1, 'p5');
insert into product(name, category_id, unit, external_id)
values ('Мыло', 2, 1, 'p6');
insert into product(name, category_id, unit, external_id)
values ('Электроэнергия', 3, 1, 'p7');

insert into purchase (price, unit, purchased_at, product_id, store_id, memo, person_id, external_id)
values (1, 1, '2022-09-01 09:00:00', 1, 1, '', 1, 'prc1');

insert into purchase (price, unit, purchased_at, product_id, store_id, memo, person_id, external_id)
values (1, 1, '2022-10-01 09:00:00', 2, 2, '', 2, 'prc2');

insert into purchase (price, unit, purchased_at, product_id, store_id, memo, person_id, external_id)
values (1, 1, '2022-11-01 09:00:00', 3, 3, '', 1, 'prc3');

