----- DDL
drop table if exists person_role cascade;
create table person_role
(
    id   int primary key generated by default as identity,
    name varchar(50) not null
);

drop table if exists person cascade;
create table person
(
    id          int primary key generated by default as identity,
    login       varchar(100) not null unique,
    password    varchar(255) not null,
    first_name  varchar(50)  not null,
    last_name   varchar(50)  not null,
    role_id     int          references person_role (id) on delete set null,
    external_id varchar(30)  not null unique
);
----- DML
insert into person_role(name)
values ('ROLE_USER');
insert into person_role(name)
values ('ROLE_ADMIN');

insert into person (login, password, first_name, last_name, role_id, external_id)
values ('user', 'pwd', 'FirstUser', 'LastUser', 1, 'person1');
insert into person (login, password, first_name, last_name, role_id, external_id)
values ('admin', 'pwd', 'FirstAdmin', 'LastAdmin', 2, 'person2');