----- DDL
drop table if exists product_category cascade;
create table product_category
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null unique,
    external_id varchar(30)  not null unique
);
----- DML
insert into product_category(name, external_id)
values ('Продукты', 'pc1');
insert into product_category(name, external_id)
values ('Хозтовары', 'pc2');
insert into product_category(name, external_id)
values ('Коммунальные услуги', 'pc3');
