----- DDL
drop table if exists product_category cascade;
create table product_category
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null unique,
    external_id varchar(30)  not null unique
);

drop table if exists product cascade;
create table product
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null,
    category_id int          references product_category (id) on delete set null,
    unit        float8       not null check ( unit > 0),
    external_id varchar(30)  not null unique,
    unique (name, category_id)
);
----- DML
insert into product_category(name, external_id)
values ('Продукты', 'pc1');
insert into product_category(name, external_id)
values ('Хозтовары', 'pc2');
insert into product_category(name, external_id)
values ('Коммунальные услуги', 'pc3');

insert into product(name, category_id, unit, external_id)
values ('Хлеб ржаной', 1, 1, 'p1');
insert into product(name, category_id, unit, external_id)
values ('Хлеб белый', 1, 1, 'p2');
insert into product(name, category_id, unit, external_id)
values ('Кефир', 1, 1, 'p3');
insert into product(name, category_id, unit, external_id)
values ('Мыло', 2, 1, 'p4');
insert into product(name, category_id, unit, external_id)
values ('Электроэнергия', 3, 1, 'p5');