----- DDL
drop table if exists person_role cascade;
create table person_role
(
    id   int primary key generated by default as identity,
    name varchar(50) not null
);
----- DML
insert into person_role(name)
values ('ROLE_USER');
insert into person_role(name)
values ('ROLE_ADMIN');